stages:
 - build
 - .post

test build job:
  image: docker:latest
  stage: build
  only:
    - develop@LHMS/SystemReports
  tags:
    - develop

  script:
    - sed -i 's/$Secret/'"$SECRET"'/g' appsettings.Staging.json
    - sed -i 's/$Emailfrom/'"$EMAILFROM"'/g' appsettings.Staging.json
    - sed -i 's/$SmtpHost/'"$SMTPHOST"'/g' appsettings.Staging.json
    - sed -i 's/$SmtpPort/'"$SMTPPORT"'/g' appsettings.Staging.json
    - sed -i 's/$SmtpUser/'"$SMTPUSER"'/g' appsettings.Staging.json
    - sed -i 's/$SmtpPass/'"$SMTPPASS"'/g' appsettings.Staging.json
    - sed -i 's/$DisplayedSender/'"$DISPLAYEDSENDER"'/g' appsettings.Staging.json
    - sed -i 's/$ConnectString/'"$CONNECTSTRING"'/g' appsettings.Staging.json
    - docker build -f test.Dockerfile -t systemreports .

test deploy job:
  stage: .post
  only:
    - develop@LHMS/SystemReports
  trigger:
    project: LHMS/LHMS
    branch: develop

prod build job:
    image: docker:latest
    stage: build
    only:
      - master@LHMS/SystemReports
    tags:
      - production

    script:
      - sed -i 's/$Secret/'"$SECRET"'/g' appsettings.Production.json
      - sed -i 's/$Emailfrom/'"$EMAILFROM"'/g' appsettings.Production.json
      - sed -i 's/$SmtpHost/'"$SMTPHOST"'/g' appsettings.Production.json
      - sed -i 's/$SmtpPort/'"$SMTPPORT"'/g' appsettings.Production.json
      - sed -i 's/$SmtpUser/'"$SMTPUSER"'/g' appsettings.Production.json
      - sed -i 's/$SmtpPass/'"$SMTPPASS"'/g' appsettings.Production.json
      - sed -i 's/$DisplayedSender/'"$DISPLAYEDSENDER"'/g' appsettings.Production.json
      - sed -i 's/$ConnectString/'"$CONNECTSTRING"'/g' appsettings.Production.json
      - docker build -f prod.Dockerfile -t systemreports .

prod deploy job:
  stage: .post
  only:
    - master@LHMS/SystemReports
  trigger:
    project: LHMS/LHMS
    branch: master
