stages:
 - build
 - .post

test build job:
  image: docker:latest
  stage: build
  only:
    - develop@LHMS/SystemReports
  tags:
    - develop
  script:
    - docker build -f test.Dockerfile -t lhmsapi .
test deploy job:
  stage: .post
  only:
    - develop@LHMS/SystemReports
  trigger:
    project: LHMS/app
    branch: develop

prod build job:
    image: docker:latest
    stage: build
    only:
      - master@LHMS/SystemReports
    tags:
      - production
    script:
      - docker build -f prod.Dockerfile -t lhmsapi .
prod deploy job:
  stage: .post
  only:
    - master@LHMS/SystemReports
  trigger:
    project: LHMS/app
    branch: master
