// <auto-generated />
using System;
using LHMS.SystemReports.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LHMS.SystemReports.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191013203000_UpdatedStatusModelFK")]
    partial class UpdatedStatusModelFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SystemName");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("BarriersOrChallenges");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CreativeIdeasAndEvaluations");

                    b.Property<string>("HowCanIHelpYou");

                    b.Property<string>("Name");

                    b.Property<string>("PersonalGrowthAndDevelopment");

                    b.Property<string>("PersonnelUpdates");

                    b.Property<DateTime>("ReportDate");

                    b.Property<int?>("SystemNameId");

                    b.Property<int?>("SystemReportStatusId");

                    b.Property<string>("SystemUpdate");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("SystemNameId");

                    b.HasIndex("SystemReportStatusId");

                    b.ToTable("SystemReports");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("SystemStatus");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemReport", b =>
                {
                    b.HasOne("LHMS.SystemReports.Models.SystemName", "SystemName")
                        .WithMany("SystemReports")
                        .HasForeignKey("SystemNameId");

                    b.HasOne("LHMS.SystemReports.Models.SystemStatus", "SystemReportStatus")
                        .WithMany()
                        .HasForeignKey("SystemReportStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
