// <auto-generated />
using System;
using LHMS.SystemReports.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LHMS.SystemReports.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220629145628_UpdateSystemNameToSystemNames")]
    partial class UpdateSystemNameToSystemNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemNames");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BarriersOrChallenges")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreativeIdeasAndEvaluations")
                        .HasColumnType("text");

                    b.Property<string>("HowCanIHelpYou")
                        .HasColumnType("text");

                    b.Property<string>("PersonalGrowthAndDevelopment")
                        .HasColumnType("text");

                    b.Property<string>("PersonnelUpdates")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportName")
                        .HasColumnType("text");

                    b.Property<string>("ReporterName")
                        .HasColumnType("text");

                    b.Property<int>("SystemNameId")
                        .HasColumnType("integer");

                    b.Property<int>("SystemReportStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemUpdate")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SystemNameId");

                    b.HasIndex("SystemReportStatusId");

                    b.ToTable("SystemReports");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemReportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemReportStatus");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemReport", b =>
                {
                    b.HasOne("LHMS.SystemReports.Models.SystemName", "SystemName")
                        .WithMany("SystemReports")
                        .HasForeignKey("SystemNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LHMS.SystemReports.Models.SystemReportStatus", "SystemReportStatus")
                        .WithMany()
                        .HasForeignKey("SystemReportStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemName");

                    b.Navigation("SystemReportStatus");
                });

            modelBuilder.Entity("LHMS.SystemReports.Models.SystemName", b =>
                {
                    b.Navigation("SystemReports");
                });
#pragma warning restore 612, 618
        }
    }
}
